### ISSUE TITLE
A great project, hoping to increase support for timeouts and proxies

### ISSUE THREAD

**Issue by ssrsec** [realgam3/requests-raw#7]
A great project, hoping to increase support for timeouts and proxies

**Comment by realgam3** [comment]
> A great project, hoping to increase support for timeouts and proxies

You can use proxies, and in the next version I fixed the use of socks proxies. about timeouts you have the same support as requests have :) so no worries.

**Comment by realgam3** [comment]
You're welcome to try v2.0.0:
https://github.com/realgam3/requests-raw/tree/v2.0.0

**Comment by realgam3** [comment]
V2.0.0 released:
https://github.com/realgam3/requests-raw/releases/tag/v2.0.0
